import { UserProfile, WorkExperience, SkillItem, EducationItem, JobListing, JobApplication, MatchAnalysis } from "@/types";

export const SEED_PROFILE: UserProfile = {
  id: "prof-nwhite-01",
  email: "whitemore@nwhite.systems",
  fullName: "Whitemore Ngwira (N. White)",
  headline: "Principal Technology Architect & AI Systems Engineer",
  summary:
    "Distinguished cloud architect and systems engineer with extensive leadership across enterprise digital platform architecture, high-throughput media systems, multi-engine databases, and governed agentic AI workflows. Architect of EarCodeX InsurTech platform, Socinga Smart Mining industrial telemetry architectures, and Cineterns / Oasis College EdTech platforms. Specialist in AWS, Next.js 15, TypeScript, LangChain/LangGraph, and zero-trust infrastructure.",
  location: "Johannesburg, South Africa / London, UK / Remote",
  targetTitles: [
    "Principal Technology Architect",
    "Lead AI Systems Engineer",
    "Director of Platform Architecture",
    "Head of Full-Stack Engineering",
    "Staff Software Architect",
  ],
  targetLocations: ["Remote (Global)", "London, UK", "EMEA Hybrid"],
  targetSalaryMin: 120000,
  targetSalaryMax: 180000,
  yearsExperience: 14,
  seniorityLevel: "Principal",
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: new Date().toISOString(),
};

export const SEED_EXPERIENCES: WorkExperience[] = [
  {
    id: "exp-1",
    profileId: "prof-nwhite-01",
    company: "N.White Systems (Independent Practice)",
    title: "Principal Technology Architect & AI Systems Engineer",
    location: "Johannesburg / London / Remote",
    startDate: "2025-01-01",
    current: true,
    summary:
      "Enterprise platform architecture, AI gateway orchestration, and cloud-native solutions for clients across insurance, mining, and education.",
    achievements: [
      "Architected and integrated AI gateways with LiteLLM (multi-model routing, token cost tracking, Bedrock/Anthropic/OpenAI failover) and Cloudflare AI Gateway across 300+ cities with edge caching and rate limiting.",
      "Delivered EarCodeX from prototype to production as an AWS cloud-native InsurTech platform, engineering automated document intelligence, claims reconciliation, immutable audit trails, and human-in-the-loop review.",
      "Engineered multi-tier AWS environments using Terraform (37 modular blueprints, S3 remote state, DynamoDB locking) with Route53 DNS, KMS envelope encryption, and Tailscale zero-trust VPN.",
      "Architected multi-engine data tiers across Amazon DynamoDB, AWS RDS PostgreSQL (Multi-AZ), ElastiCache Redis, and Neptune; built serverless data lake pipelines via AWS Lake Formation, Glue, and Athena.",
      "Designed shaft-to-mill industrial telemetry and IoT sensor data architectures from extraction points to processing mills for Socinga Smart Mining Platform.",
      "Built and deployed live edtech platforms (Cineterns and Oasis College) using Next.js, TypeScript, Claude API, Supabase, and Tailwind with multi-agent orchestration and human oversight.",
    ],
    technologies: [
      "AWS", "Next.js 15", "TypeScript", "Terraform", "Python", "Supabase",
      "PostgreSQL", "pgvector", "LiteLLM", "Docker", "Tailscale", "Redis"
    ],
  },
  {
    id: "exp-2",
    profileId: "prof-nwhite-01",
    company: "Reason GTMC",
    title: "Director of Digital Architecture & Technology",
    location: "Johannesburg, South Africa",
    startDate: "2023-01-01",
    endDate: "2025-01-01",
    current: false,
    summary:
      "Led enterprise platform architecture, digital product engineering, and high-throughput multimedia delivery systems for enterprise clients.",
    achievements: [
      "Architected Next.js and React enterprise applications, robust API gateway integrations, and component design systems embedding WCAG accessibility, Core Web Vitals optimization, and technical SEO.",
      "Deployed human-supervised generative AI pipelines for rapid requirements decomposition, automated metadata tagging, and first-pass release QA.",
      "Architected high-throughput camera-to-cloud media pipelines, checksum-verified ingest, and distributed post-production compute across 21 major productions for Netflix, MultiChoice Studios, and SABC.",
      "Advised SADC regional broadcasters on studio modernisation and engineered automated broadcast playout systems across six television networks ensuring 100% transmission stability.",
      "Directed cross-functional engineering and technical teams through Agile delivery cycles, managing cloud resource planning, security gates, and project margins.",
    ],
    technologies: ["Next.js", "React", "Node.js", "AWS S3 Glacier", "Enterprise API Gateways", "PostgreSQL", "Agile"],
  },
];

export const SEED_SKILLS: SkillItem[] = [
  { id: "sk-1", profileId: "prof-nwhite-01", name: "Cloud Architecture (AWS)", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-2", profileId: "prof-nwhite-01", name: "Next.js 15 / React 19", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-3", profileId: "prof-nwhite-01", name: "TypeScript", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-4", profileId: "prof-nwhite-01", name: "AI Gateways & Model Routing", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-5", profileId: "prof-nwhite-01", name: "LangChain & LangGraph", category: "Technical", proficiency: "Advanced", verified: true },
  { id: "sk-6", profileId: "prof-nwhite-01", name: "PostgreSQL & pgvector RAG", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-7", profileId: "prof-nwhite-01", name: "Terraform & Infrastructure as Code", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-8", profileId: "prof-nwhite-01", name: "Supabase Architecture", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-9", profileId: "prof-nwhite-01", name: "Distributed Systems & Telemetry", category: "Technical", proficiency: "Expert", verified: true },
  { id: "sk-10", profileId: "prof-nwhite-01", name: "Zero-Trust Security & Tailscale", category: "Technical", proficiency: "Advanced", verified: true },
  { id: "sk-11", profileId: "prof-nwhite-01", name: "Engineering Leadership", category: "Leadership", proficiency: "Expert", verified: true },
  { id: "sk-12", profileId: "prof-nwhite-01", name: "System Design & Governance", category: "Domain", proficiency: "Expert", verified: true },
];

export const SEED_EDUCATIONS: EducationItem[] = [
  {
    id: "edu-1",
    profileId: "prof-nwhite-01",
    institution: "Executive MBA Institute",
    degree: "Executive Master of Business Administration (EMBA)",
    fieldOfStudy: "Business Strategy & Technology Leadership",
    startDate: "2023-01-01",
  },
  {
    id: "edu-2",
    profileId: "prof-nwhite-01",
    institution: "University of the Witwatersrand",
    degree: "Bachelor of Arts Honours",
    fieldOfStudy: "Journalism & Media Studies",
    startDate: "2010-01-01",
    endDate: "2014-12-01",
  },
];

export const SEED_JOBS: JobListing[] = [
  {
    id: "job-sa-201",
    externalId: "synthesia-sa-2026-01",
    source: "direct_portal",
    title: "Principal Agentic AI Systems Architect",
    company: "Synthesia",
    companyLogoUrl: "",
    location: "Johannesburg, South Africa / Remote",
    remoteType: "Hybrid",
    salaryMin: 130000,
    salaryMax: 165000,
    currency: "GBP",
    description:
      "Synthesia is expanding its systems engineering and AI workflow infrastructure across Africa and EMEA. Leading architecture for distributed AI workflows, stateful agent orchestration with LangGraph, pgvector RAG, and multi-model gateway governance.",
    requirements: [
      "10+ years experience in distributed systems architecture and AI leadership",
      "Proven production delivery of stateful agentic workflows (LangGraph, LangChain)",
      "High-throughput vector database systems (pgvector, PostgreSQL)",
      "Multi-cloud architectures (AWS, Cloudflare AI Gateway, Vercel)",
      "Zero-trust security, Tailscale, and immutable audit trails",
    ],
    responsibilities: [
      "Architect and ship fault-tolerant agentic orchestration pipelines across enterprise clients",
      "Lead cross-functional engineering teams with rigorous code standards and ADRs",
      "Govern multi-model routing under zero-cost free-tier architectural constraints",
    ],
    skills: ["AI Systems", "LangGraph", "LangChain", "AWS", "pgvector", "TypeScript", "Next.js 15", "AI Gateways"],
    applyUrl: "https://www.synthesia.io/careers",
    postedAt: "2026-09-15T08:00:00Z",
    createdAt: "2026-09-15T08:00:00Z",
  },
  {
    id: "job-zw-202",
    externalId: "econet-zw-2026-02",
    source: "direct_portal",
    title: "Lead Cloud & AI Solutions Architect",
    company: "Econet Wireless",
    companyLogoUrl: "",
    location: "Harare, Zimbabwe / Remote",
    remoteType: "Remote",
    salaryMin: 120000,
    salaryMax: 155000,
    currency: "GBP",
    description:
      "Econet Wireless is seeking a Lead Cloud & AI Solutions Architect to engineer multi-tier cloud infrastructure on AWS and architect enterprise AI model routing with LiteLLM and Cloudflare across African telecommunications and financial infrastructure.",
    requirements: [
      "8+ years software and cloud architecture experience with AWS and Terraform",
      "Experience deploying production AI gateways and model routing architectures",
      "Demonstrated ability to design telemetry architectures and industrial IoT data pipelines",
      "Expertise in PostgreSQL, TypeScript, and modern distributed systems",
    ],
    responsibilities: [
      "Architect cloud-native platforms with Terraform modular blueprints and remote state",
      "Deploy low-latency AI gateway caching across edge points of presence",
      "Coordinate with engineering leadership across regional African hubs",
    ],
    skills: ["Cloud Architecture", "AWS", "LiteLLM", "Terraform", "PostgreSQL", "AI Systems", "Zero-Trust"],
    applyUrl: "https://www.econet.co.zw/",
    postedAt: "2026-09-15T12:00:00Z",
    createdAt: "2026-09-15T12:00:00Z",
  },
  {
    id: "job-101",
    externalId: "entelect-za-489211",
    source: "direct_portal",
    title: "Lead Solutions Architect (AI & Cloud Platforms)",
    company: "Entelect",
    companyLogoUrl: "",
    location: "Johannesburg, South Africa (Hybrid / Remote Option)",
    remoteType: "Hybrid",
    salaryMin: 135000,
    salaryMax: 160000,
    currency: "GBP",
    description:
      "Entelect is hiring a Lead Solutions Architect to direct enterprise software architecture, Next.js modern platforms, pgvector semantic search, and AI-enabled cloud infrastructure for top-tier African and international corporate clients.",
    requirements: [
      "10+ years software engineering with at least 3+ years in architectural leadership",
      "Expert mastery of Next.js 14/15 App Router, React Server Components, and TypeScript",
      "Demonstrated delivery of production RAG systems utilizing pgvector or vector databases",
      "Hands-on experience with AI model routing, prompt engineering, and token optimization",
      "Proven cloud architecture skills in AWS or Supabase",
    ],
    responsibilities: [
      "Architect and ship high-throughput enterprise SaaS applications with 99.9% uptime",
      "Design multi-agent LLM workflows and ensure zero-hallucination factual grounding",
      "Collaborate with product and executive teams on system design and technical roadmap",
    ],
    skills: ["Next.js 15", "TypeScript", "pgvector", "LangGraph", "Supabase", "AWS", "AI Gateways"],
    applyUrl: "https://culture.entelect.co.za/join-us/",
    postedAt: "2026-09-14T09:00:00Z",
    createdAt: "2026-09-14T09:00:00Z",
  },
  {
    id: "job-102",
    externalId: "iqbusiness-za-902",
    source: "direct_portal",
    title: "AI Solutions Architect",
    company: "IQbusiness",
    companyLogoUrl: "",
    location: "Johannesburg, South Africa",
    remoteType: "Hybrid",
    salaryMin: 145000,
    salaryMax: 175000,
    currency: "GBP",
    description:
      "IQbusiness is hiring an AI Solutions Architect in Johannesburg to lead client enterprise AI adoption, cloud architecture on AWS Bedrock, agentic automation, and zero-trust telemetry systems.",
    requirements: [
      "Deep experience designing resilient distributed systems and asynchronous event architectures",
      "Mastery of multi-agent architectures (LangGraph, AutoGen, or custom state machines)",
      "Strong background with Python, TypeScript, and multi-engine PostgreSQL stores",
      "Zero-trust security and infrastructure-as-code (Terraform)",
    ],
    responsibilities: [
      "Design autonomous agentic orchestration layers with robust fallback mechanisms",
      "Lead cross-functional technical teams and establish engineering quality bars",
      "Ensure compliance and auditability across all AI operations",
    ],
    skills: ["AI Systems", "AWS", "Bedrock", "Generative AI", "Agentic AI", "Solutions Architecture"],
    applyUrl: "https://iqbusiness.net/careers",
    postedAt: "2026-09-13T14:30:00Z",
    createdAt: "2026-09-13T14:30:00Z",
  },
  {
    id: "job-103",
    externalId: "aws-za-78190",
    source: "direct_portal",
    title: "Senior Cloud Solutions Architect (AI/ML)",
    company: "Amazon Web Services",
    companyLogoUrl: "",
    location: "Cape Town, South Africa",
    remoteType: "Hybrid",
    salaryMin: 150000,
    salaryMax: 180000,
    currency: "GBP",
    description:
      "Amazon Web Services (AWS) Cape Town is seeking a Senior Cloud Solutions Architect to consult with enterprise customers across Sub-Saharan Africa on scalable cloud architecture, modern web applications, and generative AI deployments.",
    requirements: [
      "Proven track record as a Solutions Architect for enterprise cloud and AI platforms",
      "Executive communication skills with ability to lead C-suite and technical stakeholders",
      "Hands-on expertise across AWS cloud infrastructure, multi-engine databases, and modern systems",
    ],
    responsibilities: [
      "Establish enterprise cloud architecture governance and technical blueprints",
      "Drive AI and GenAI operationalisation to accelerate product engineering iteration",
      "Oversee cloud infrastructure budget, security postures, and project reliability",
    ],
    skills: ["Enterprise Architecture", "Cloud Strategy", "Executive Leadership", "AWS", "AI Governance"],
    applyUrl: "https://www.amazon.jobs/en/locations/cape-town-south-africa",
    postedAt: "2026-09-12T11:00:00Z",
    createdAt: "2026-09-12T11:00:00Z",
  },
  {
    id: "job-104",
    externalId: "takealot-za-114",
    source: "direct_portal",
    title: "Lead Platform & Infrastructure Architect",
    company: "Takealot Group",
    companyLogoUrl: "",
    location: "Cape Town, South Africa",
    remoteType: "Hybrid",
    salaryMin: 110000,
    salaryMax: 130000,
    currency: "GBP",
    description:
      "Takealot Group is South Africa's premier e-commerce platform. We are seeking a Lead Platform & Infrastructure Architect to oversee high-throughput platform services, resilient multi-engine database pipelines, and cloud systems.",
    requirements: [
      "5+ years full-stack web engineering with TypeScript and React/Next.js",
      "Solid understanding of relational database schema design, RLS, and SQL performance",
      "Familiarity with financial or high-throughput e-commerce compliance",
    ],
    responsibilities: [
      "Build sleek, accessible UI components and data systems with responsive design",
      "Implement server actions, API routes, and database migrations",
    ],
    skills: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "REST APIs"],
    applyUrl: "https://www.takealot.com/about/careers",
    postedAt: "2026-09-11T16:00:00Z",
    createdAt: "2026-09-11T16:00:00Z",
  },
];

export const SEED_MATCH_ANALYSES: Record<string, MatchAnalysis> = {
  "job-101": {
    id: "match-101",
    jobId: "job-101",
    profileId: "prof-nwhite-01",
    overallScore: 96,
    tier: "strong_match",
    breakdown: [
      {
        category: "Technical Stack (Next.js, TS, Supabase, pgvector)",
        score: 98,
        weight: 0.4,
        matchedSkills: ["Next.js 15", "TypeScript", "pgvector", "Supabase", "AI Gateways"],
        missingSkills: [],
        notes: "Flawless direct match. Production experience with EarCodeX and Cineterns.",
      },
      {
        category: "Architectural Seniority & Leadership",
        score: 95,
        weight: 0.35,
        matchedSkills: ["Principal Architecture", "System Design", "Agile Leadership"],
        missingSkills: [],
        notes: "14+ years experience exceeds the 10+ years requirement.",
      },
      {
        category: "Domain & AI Governance",
        score: 94,
        weight: 0.25,
        matchedSkills: ["Model Routing", "Zero-Hallucination Controls", "Document Intelligence"],
        missingSkills: [],
        notes: "EarCodeX and LiteLLM experience directly maps to their requirements.",
      },
    ],
    keyStrengths: [
      "Proven architecture of live enterprise platforms combining Next.js 15, Supabase, and AI Gateways.",
      "Extensive experience with LiteLLM and Cloudflare AI Gateway multi-model routing.",
      "Deep understanding of pgvector semantic search and zero-hallucination grounding.",
    ],
    criticalGaps: ["None identified. Highly aligned with job requirements."],
    recommendedAction: "High-priority immediate application. Lead with EarCodeX and AI Gateway production case studies.",
    modelUsed: "google/gemini-2.0-flash-thinking-exp:free",
    createdAt: "2026-09-14T10:00:00Z",
  },
  "job-102": {
    id: "match-102",
    jobId: "job-102",
    profileId: "prof-nwhite-01",
    overallScore: 94,
    tier: "strong_match",
    breakdown: [
      {
        category: "Agentic Systems & Distributed Architecture",
        score: 95,
        weight: 0.45,
        matchedSkills: ["Multi-Agent RAG", "LangGraph", "Distributed Systems", "IoT Telemetry"],
        missingSkills: [],
        notes: "Socinga Smart Mining and EarCodeX demonstrate large-scale distributed telemetry.",
      },
      {
        category: "Infrastructure as Code & Security",
        score: 96,
        weight: 0.3,
        matchedSkills: ["Terraform (37 blueprints)", "Zero-Trust (Tailscale)", "AWS IAM"],
        missingSkills: [],
        notes: "Exceptional infrastructure-as-code credentials.",
      },
      {
        category: "Programming Runtimes (Python & TypeScript)",
        score: 90,
        weight: 0.25,
        matchedSkills: ["TypeScript", "Python", "PostgreSQL"],
        missingSkills: ["Kubernetes (Minor preference)"],
        notes: "Strong Python/TypeScript capability; Kubernetes demonstrated in DevOps module.",
      },
    ],
    keyStrengths: [
      "Direct experience architecting multi-engine database pipelines and telemetry streaming.",
      "37 modular Terraform blueprints with zero-trust network design.",
    ],
    criticalGaps: ["Highlight Kubernetes container orchestration during technical discussion."],
    recommendedAction: "Apply with custom CV tailored towards distributed systems and autonomous agent state machines.",
    modelUsed: "google/gemini-2.0-flash-thinking-exp:free",
    createdAt: "2026-09-14T11:30:00Z",
  },
};

export const SEED_APPLICATIONS: JobApplication[] = [
  {
    id: "app-201",
    profileId: "prof-nwhite-01",
    jobId: "job-101",
    status: "interviewing",
    appliedDate: "2026-09-14",
    deadline: "2026-09-28",
    notes: "Technical architecture presentation scheduled. Key topic: Multi-model failover and pgvector index scaling.",
    interviewStages: [
      { stage: "CV Screen", scheduledAt: "2026-09-14T14:00:00Z", completed: true, notes: "Recruiter impressed by EarCodeX production deployment." },
      { stage: "Architecture Deep-Dive", scheduledAt: "2026-09-18T10:00:00Z", completed: false, notes: "Presenting system design diagram and live ApplyWise AI demo." },
    ],
    createdAt: "2026-09-14T12:00:00Z",
    updatedAt: "2026-09-14T16:00:00Z",
    job: SEED_JOBS[0],
    matchAnalysis: SEED_MATCH_ANALYSES["job-101"],
  },
  {
    id: "app-202",
    profileId: "prof-nwhite-01",
    jobId: "job-102",
    status: "ready",
    appliedDate: undefined,
    deadline: "2026-09-30",
    notes: "Tailored CV and Cover letter generated. ATS match score: 94%. Ready for submission.",
    interviewStages: [],
    createdAt: "2026-09-13T16:00:00Z",
    updatedAt: "2026-09-14T08:00:00Z",
    job: SEED_JOBS[1],
    matchAnalysis: SEED_MATCH_ANALYSES["job-102"],
  },
  {
    id: "app-203",
    profileId: "prof-nwhite-01",
    jobId: "job-103",
    status: "tailoring",
    appliedDate: undefined,
    deadline: "2026-10-05",
    notes: "Tailoring executive pitch emphasizing board-level technical leadership and SADC studio modernisation.",
    createdAt: "2026-09-12T12:00:00Z",
    updatedAt: "2026-09-12T12:00:00Z",
    job: SEED_JOBS[2],
  },
];
