apiVersion: v1
kind: ConfigMap
metadata:
  name: applywise-ai-config
  namespace: applywise-ai
  labels:
    app.kubernetes.io/name: applywise-ai
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_APP_NAME: "ApplyWise AI"
  NEXT_PUBLIC_APP_URL: "http://applywise-ai.applywise-ai.svc.cluster.local:3000"
