apiVersion: v1
kind: ServiceAccount
metadata:
  name: applywise-ai-sa
  namespace: applywise-ai
  labels:
    app.kubernetes.io/name: applywise-ai
    app.kubernetes.io/component: service-account
automountServiceAccountToken: false
